### ISSUE TITLE
Mount Button large number of mounts

### ISSUE THREAD

**Issue by jasskin** [Korbl/AutoBarWoTLK#6]
So I am a collector I have 60 mounts currently and they are not all showing up I assume its a limit of some sort as the mounts displayed changed when I learned new mounts recently.  I could test this by rearranging the ID order to see if different mounts display, I'll try to do this today.  Currently only 37 mounts Display. 

![image](https://user-images.githubusercontent.com/607238/190865280-a78315d2-5bd9-4a47-82be-2bea52c0d581.png)

My bcc version 40 mounts display.

![image](https://user-images.githubusercontent.com/607238/190865463-6ba674a9-a13f-4b57-bbee-f754360a4dee.png)

**Comment by Korbl** [comment]
MuffinManKen is back, Closing this repo and working on his: https://github.com/MuffinManKen/AutoBar
